"""Added SegmentSpeed table to persist physics engine learning

Revision ID: 31772bf6e430
Revises: 20260706_0002
Create Date: 2026-09-26 20:51:57.309962
"""

from alembic import op
import sqlalchemy as sa


revision = '31772bf6e430'
down_revision = '20260706_0002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

