import uuid
from models import db
from datetime import datetime, timezone

class Favorite(db.Model):
    __tablename__ = "favorites"

    id = db.Column(db.String(120), primary_key=True, default=lambda: str(uuid.uuid4())) # UUID string generated by client or server
    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False, index=True)
    type = db.Column(db.String(50), nullable=False)
    category = db.Column(db.String(50), nullable=False)
    title = db.Column(db.String(255), nullable=False)
    subtitle = db.Column(db.String(255), nullable=True)
    
    route_id = db.Column(db.String(120), nullable=True)
    stop_id = db.Column(db.String(120), nullable=True)
    latitude = db.Column(db.Float, nullable=True)
    longitude = db.Column(db.Float, nullable=True)
    
    icon = db.Column(db.String(120), nullable=True)
    color = db.Column(db.String(50), nullable=True)
    sort_order = db.Column(db.Integer, default=0)
    status = db.Column(db.String(30), default="ACTIVE", nullable=False)
    
    last_used = db.Column(db.DateTime, nullable=True)
    usage_count = db.Column(db.Integer, default=0, nullable=False)
    collection_id = db.Column(db.String(120), nullable=True)
    device_id = db.Column(db.String(120), nullable=True)
    
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc), onupdate=lambda: datetime.now(timezone.utc), nullable=False)

    user = db.relationship("User", back_populates="favorites")

    def __repr__(self) -> str:
        return f"<Favorite {self.title} ({self.category})>"
